<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <Using Include="Kentico.Xperience.ComponentRegistry.MCP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kentico.Xperience.ComponentRegistry\Kentico.Xperience.ComponentRegistry.csproj" />
    <ProjectReference Include="..\..\src\Kentico.Xperience.ComponentRegistry.MCP\Kentico.Xperience.ComponentRegistry.MCP.csproj" />
  </ItemGroup>

</Project>
